config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations" }

  # to make logout work with get request
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session_via_get
  end

  get "user_list" => "user_list#index", as: :user_list
  delete "user_list/delete/:id", to: "user_list#delete", as: :delete_student
  post "user_list/approve/:id", to: "user_list#approve", as: :approve_student

  get "requests" => "request#index", as: :requests
  get "requests/new" => "request#new", as: :new_request
  post "requests" => "request#create", as: :create_request

  get "requests/:request_id/responses/new" => "response#new", as: :request_responses
  post "requests/:request_id/responses/new" => "response#create", as: :create_response

  get "requests/:request_id/" => "request#view", as: :view_responses
  delete "requests/delete/:request_id" => "request#delete", as: :delete_request

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  serialize :dates, type: Array, coder: JSON
  has_many :responses, dependent: :destroy
  validates :due_date, presence: true
  validates :dates, presence: true
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_tutor

  def index
    @requests = Request.left_outer_joins(:responses)
                       .select("requests.*, COUNT(responses.id) AS responses_count").group("requests.id")

    @number_of_students = User.where(role: "student").count
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    if @request.save
      flash[:notice] = "Request created successfully"
      redirect_to requests_path
    else
      flash[:error] = @request.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def view
    @request = Request.find(params[:request_id])
    @responses = @request.responses
    @tutor_name = @request.user.name + " " + @request.user.surname
  end

  def delete
    @request = Request.find(params[:request_id])
    if @request.destroy
      flash[:notice] = "Request deleted successfully"
      redirect_to requests_path
    else
      flash[:error] = @request.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def request_params
    params.require(:request).permit(:due_date, dates: []) # Allow "dates" as an array
  end

  def ensure_tutor
    redirect_to root_path unless current_user.tutor?
  end

end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/request/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between flex-row gap-1 border p-2">
    <h5 style="margin-bottom: 0;">Lista richieste presenze</h5>
    <div class="d-flex gap-1 flex-row">
      <%= link_to "Nuova Richiesta", new_request_path, class: "btn btn-sm btn-success" %>
      <%= link_to "Torna alla home  ", _back_url, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
  <div class="border p-2">
    <table class="table table-striped table-bordered table-hover mb-0">
      <thead>
      <tr>
        <th scope="col">Data creazione</th>
        <th scope="col">Data di scadenza</th>
        <th scope="col">Giorni di presenza</th>
        <th scope="col">Num. risposte</th>
        <th scope="col" style="width: 1px;">Azioni</th>
      </tr>
      </thead>
      <tbody>
      <% @requests.each do |request| %>
        <tr>
          <td><%= I18n.l(request.created_at.in_time_zone("Europe/Rome"), format: :short) %></td>
          <td>
            <% if request.due_date < Date.today %>
              <span class="badge text-bg-danger"><%= I18n.l(request.due_date, format: :default) %></span>
            <% else %>
              <span class="badge text-bg-success"><%= I18n.l(request.due_date, format: :default) %></span>
            <% end %>
          </td>
          <td>
            <span class="badge text-bg-secondary" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-html="true"
                  data-bs-title="
                      <% request.dates.each do |date| %>
                         - <%= I18n.l(Date.parse(date), format: :default) %> <br/>
                      <% end %>
                       ">
                  Mostra date
                </span>
          </td>
          <td><%= request.responses_count %> / <%= @number_of_students %></td>
          <td>
            <div class="d-flex flex-row gap-1">
              <%= link_to "Risposte", view_responses_path(request), class: "btn btn-sm btn-primary" %>
              <%= link_to "Notifica", requests_path(request), class: "btn btn-sm btn-primary" %>
              <%= button_to "Elimina", delete_request_path(request), method: :delete, class: "btn btn-sm btn-danger" %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

app/views/request/new.html.erb
<div class="container mt-3">
  <div class="alert alert-warning mt-1 mb-3" role="alert">
    <i class="bi bi-exclamation-triangle"></i>
    <b>Attenzione!</b> Una volta salvata non è possibile modificare la richiesta.
  </div>
  <div class="d-flex justify-content-between flex-row gap-1 border p-2">
    <h5 style="margin-bottom: 0;">Nuova richiesta presenze</h5>
    <div class="d-flex gap-1 flex-row">
      <%= link_to "Torna indietro  ", _back_url, class: "btn btn-sm btn-primary" %>
    </div>
  </div>

  <%= form_with model: @request, local: true do |form| %>
    <!-- Hidden Field for User ID -->
    <%= form.hidden_field :user_id, value: session[:user_id] %>

    <!-- Due Date Field -->
    <div class="form-floating mt-1 mb-1">
      <%= form.date_field :due_date, class: "form-control" %>
      <%= form.label :due_date, "Data di scadenza della richiesta" %>
    </div>

    <!-- Notes Field -->
    <div class="mt-1 mb-1">
      <div class="d-flex justify-content-between flex-row gap-1 border p-2 mb-1">
        <b>Note aggiuntive</b>
      </div>
      <%= form.text_area :notes, class: "form-control", placeholder: "note..." %>
    </div>

    <!-- Dates Field (Dynamic List) -->
    <div class="form-group mt-2">
      <div class="d-flex justify-content-between flex-row gap-1 border p-2 mb-1">
        <b>Giorni di presenza</b>
      </div>
      <div id="dates-fields">
        <div class="d-flex flex-row gap-1 mb-1">
          <input type="date" name="request[dates][]" class="form-control" />
          <button type="button" class="btn btn-danger remove-date" onclick="removeDateField(this)">
            <i class="bi bi-trash"></i>
          </button>
        </div>
      </div>
      <div class="w-100 d-flex flex-row justify-content-end">
        <button type="button" id="add-date" class="btn btn-success">
          <i class="bi bi-plus-circle"></i>
        </button>
      </div>
    </div>

    <!-- Submit Button -->
    <div class="w-100 d-flex flex-row justify-content-center mt-1">
      <%= form.submit "Crea Richiesta", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        const addDateButton = document.getElementById("add-date");
        const datesContainer = document.getElementById("dates-fields");

        // Add a new date field
        addDateButton.addEventListener("click", () => {
            const dateField = document.createElement("div");
            dateField.classList.add("d-flex");
            dateField.classList.add("flex-row");
            dateField.classList.add("gap-1");
            dateField.classList.add("mb-1");
            dateField.innerHTML = `
              <input type="date" name="request[dates][]" class="form-control" />
              <button type="button" class="btn btn-danger remove-date" onclick="removeDateField(this)">
                <i class="bi bi-trash"></i>
              </button>
    `;
            datesContainer.appendChild(dateField);
        });
    });

    // Function to remove a specific date field
    function removeDateField(button) {
        button.parentElement.remove();
    }
</script>

app/views/request/view.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between flex-row gap-1 border p-2">
    <h5 style="margin-bottom: 0;">Risposte alla richiesta</h5>
    <div class="d-flex gap-1 flex-row">
      <%= link_to "Torna indietro  ", _back_url, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
  <div class="border w-100 p-2">
    <strong>Tutor:</strong> <%= @tutor_name %> <br>
    <strong>Data richiesta:</strong> <%= I18n.l(@request.created_at, format: :short) %> <br>
    <strong>Data scadenza:</strong> <%= I18n.l(@request.due_date, format: :default) %> <br>
    <% unless @request.annotations.blank?  %>
      <strong>Annotazioni del tutor:</strong><br>
      <%= @request.annotations %> <br>
    <% end %>
  </div>
  <div class="border p-2">
    <table class="table table-striped table-bordered table-hover mb-0">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Cognome</th>
        <% @request.dates.each do |date| %>
          <th><%= I18n.l(Date.parse(date), format: :default) %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @responses.each do |response| %>
        <tr>
          <td><%= response.user.name %></td>
          <td><%= response.user.surname %></td>
          <% @request.dates.each do |date| %>
            <td>
              <% if response.present_on?(date) %>
                <span class="badge text-bg-success">Presente</span>
              <% else %>
                <span class="badge text-bg-danger">Assente</span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>