config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations" }

  # to make logout work with get request
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session_via_get
  end

  get "user_list" => "user_list#index", as: :user_list
  delete "user_list/delete/:id", to: "user_list#delete", as: :delete_student
  post "user_list/approve/:id", to: "user_list#approve", as: :approve_student

  get "requests" => "request#index", as: :requests
  get "requests/new" => "request#new", as: :new_request
  post "requests" => "request#create", as: :create_request

  get "requests/:request_id/responses/new" => "response#new", as: :request_responses
  post "requests/:request_id/responses/new" => "response#create", as: :create_response

  get "requests/:request_id/" => "request#view", as: :view_responses
  delete "requests/delete/:request_id" => "request#delete", as: :delete_request

end

app/controllers/user_list_controller.rb
class UserListController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_tutor

  def index
    @users = User.where(role: "student")
  end

  def delete
    user = User.find(params[:id])
    if user.tutor?
      flash[:error] = "Non sei autorizzato a eseguire questa azione."
      redirect_to user_list_path
      return
    end
    user.destroy
    redirect_to user_list_path, notice:
  end
  def approve
    user = User.find(params[:id])
    if user.tutor?
      flash[:error] = "Non sei autorizzato a eseguire questa azione."
      redirect_to user_list_path
      return
    end
    unless user.update_column(:approved_from_tutor, true)
      flash[:error] = "Errore durante l'approvazione."
    end
    redirect_to user_list_path, notice:
  end

  private

  def ensure_tutor
    redirect_to root_path unless current_user.tutor?
  end

end

app/helpers/user_list_helper.rb
module UserListHelper
end

app/views/user_list/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between flex-row gap-1 border p-2">
    <h5 style="margin-bottom: 0;">Lista studenti registrati</h5>
    <%= link_to "Torna alla home  ", _back_url, class: "btn btn-sm btn-primary" %>
  </div>
  <% if @users.any? %>
    <table class="table table-striped table-bordered mt-1">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Cognome</th>
        <th>Email</th>
        <th style="width: 1px">Azioni</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td><%= user.email %></td>
          <td class="d-flex justify-content-center flex-row gap-1">
            <% unless user.approved_from_tutor %>
            <%= button_to 'Approva', approve_student_path(user), method: :post, class: "btn btn-sm btn-success" %>
            <%  end %>
            <%= button_to 'Elimina', delete_student_path(user), method: :delete, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div style="text-align: center;">
      <b>Nessuno studente trovato.</b>
      <%= link_to "Torna indietro", _back_url %>
    </div>
  <% end %>
</div>