config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations" }

  # to make logout work with get request
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session_via_get
  end

  get "user_list" => "user_list#index", as: :user_list
  delete "user_list/delete/:id", to: "user_list#delete", as: :delete_student
  post "user_list/approve/:id", to: "user_list#approve", as: :approve_student

  get "requests" => "request#index", as: :requests
  get "requests/new" => "request#new", as: :new_request
  post "requests" => "request#create", as: :create_request

  get "requests/:request_id/responses/new" => "response#new", as: :request_responses
  post "requests/:request_id/responses/new" => "response#create", as: :create_response

  get "requests/:request_id/" => "request#view", as: :view_responses
  delete "requests/delete/:request_id" => "request#delete", as: :delete_request

end

app/controllers/home_controller.rb
include HomeHelper
class HomeController < ApplicationController
  PAGE_URL = "https://aiuto.elis.org/menu/"
  def index
    @menu_data = fetch_menu_data(PAGE_URL)

    if current_user&.student?
      @requests_without_response = Request.where.not(
        id: Response.where(user_id: current_user.id).pluck(:request_id),
      ).where("due_date > ?", Date.today)
    else
      @requests_without_response = []
    end

    render :index
  end

end

app/helpers/home_helper.rb
require "httparty"
require "nokogiri"

module HomeHelper
  def fetch_menu_data(page_url)
    response = HTTParty.get(page_url)
    doc = Nokogiri::HTML(response.body)

    sections = doc.css(".row.mr-1.ml-2.mt-1.mb-1").first&.elements || []
    sections.map do |section|
      {
        title: section.at_css(".pietanze")&.text&.strip,
        items: parse_items(section)
      }
    end
  end

  def parse_items(section)
    items_container = section.at_css(".col-12.text-left")&.elements || []
    items_container.each_slice(2).map do |item_element, ingredient_element|
      next unless item_element

      {
        name: item_element.text.gsub("-", "").strip,
        glutenFree: item_element.at_css("img[src='/Menu/img/gluten.png']").present?,
        lactoseFree: item_element.at_css("img[src='/Menu/img/lactose.png']").present?,
        ingredientiAllergeni: extract_allergens(ingredient_element),
        ingredienti: extract_ingredients(ingredient_element)
      }
    end.compact
  end

  def extract_allergens(ingredient_element)
    return [] unless ingredient_element

    allergens = ingredient_element.css("strong").map { |tag| tag.text.gsub(",", "") }
    ingredient_element.css("strong").remove # Remove strong tags from original HTML
    allergens
  end

  def extract_ingredients(ingredient_element)
    return [] unless ingredient_element

    ingredients_text = ingredient_element.text.gsub(/[()\n\r]/, "").strip
    ingredients_text.split(", ").map(&:strip)
  end
end

app/views/home/index.html.erb
<main class="container py-3">
  <% if current_user&.tutor? %>
    <div class="alert alert-primary mb-2 padding-alert-buttons">
      <div class="row">
        <div class="col d-flex align-items-center">
          <b>
            <i class="bi bi-universal-access me-2"></i>
            FUNZIONI TUTOR
          </b>
        </div>
        <div class="col-auto d-flex flex-row gap-1">
          <%= link_to "Richieste", requests_path, class: "btn btn-primary" %>
          <%= link_to "Lista Utenti", user_list_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user&.student? and @requests_without_response %>
    <% @requests_without_response.each do |request| %>
      <div class="alert alert-warning d-flex justify-content-between align-items-center mb-1">
    <span>
      <i class="bi bi-exclamation-triangle-fill me-2"></i>
      <b>Richiesta in attesa di risposta! </b><br>
      <b>Data richiesta:</b>
      <%= I18n.l(request.created_at.in_time_zone("Europe/Rome"), format: :short) %><br>
      <b>Scadenza:</b>
      <%= I18n.l(Date.parse(request.due_date.to_s), format: :default) %>
    </span>
        <%= link_to "Rispondi", request_responses_path(request), class: "btn btn-warning" %>
      </div>
    <% end %>
  <% end %>

  <% if @menu_data == nil %>
    <div class="alert alert-primary" role="alert">
      <i class="bi bi-info-circle-fill me-2"></i>
      <%= t("data_not_published") %>
    </div>
  <% else %>
    <div class="d-flex justify-content-between align-items-center mb-4 rounded border padding-alert-buttons">
      <p class="mb-0 fw-bold"><%= t("last_fetched") %>: <%= Time.now.strftime("%d/%m/%Y %H:%M") %></p>
      <%= button_to t("reload_page"), root_path, method: :get, class: "btn btn-primary" %>
    </div>

    <% @menu_data.each do |section| %>
      <div class="mb-4">
        <h2 class="h4 fw-semibold mb-3"><%= section[:title] %></h2>

        <% section[:items].each do |item| %>
          <div class="border rounded p-3 mb-3">
            <h3 class="h5 fw-medium mb-2"><%= item[:name] %></h3>
            <div>
              <strong><%= t("gluten_free") %>:</strong>
              <%= item[:glutenFree] ? t("yesword") : "No" %>
            </div>
            <div>
              <strong><%= t("lactose_free") %>:</strong>
              <%= item[:lactoseFree] ? t("yesword") : 'No' %>
            </div>
            <% if item[:ingredienti].present? %>
              <div>
                <strong><%= t("ingredients") %>:</strong>
                <%= item[:ingredienti].join(", ") %>
              </div>
            <% end %>
            <% if item[:ingredientiAllergeni].present? %>
              <div>
                <strong><%= t("allergic_ingredients") %>:</strong>
                <%= item[:ingredientiAllergeni].join(", ") %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</main>