config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations" }

  # to make logout work with get request
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session_via_get
  end

  get "user_list" => "user_list#index", as: :user_list
  delete "user_list/delete/:id", to: "user_list#delete", as: :delete_student
  post "user_list/approve/:id", to: "user_list#approve", as: :approve_student

  get "requests" => "request#index", as: :requests
  get "requests/new" => "request#new", as: :new_request
  post "requests" => "request#create", as: :create_request

  get "requests/:request_id/responses/new" => "response#new", as: :request_responses
  post "requests/:request_id/responses/new" => "response#create", as: :create_response

  get "requests/:request_id/" => "request#view", as: :view_responses
  delete "requests/delete/:request_id" => "request#delete", as: :delete_request

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= t("lang") %>">
<head>
  <title><%= content_for(:title) || "Mensa ELIS Esterni" %></title>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= yield :head %>
  <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
  <%= render 'pwa/favicon' %>
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<div class="d-flex flex-column vh-100">
  <header class="p-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-between">
        <a href="<%= root_path %>"
           class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <%= image_tag "logo.png", alt: "Logo ELIS", class: "bi me-2", height: "30" %>
        </a>
        <div class="text-end">
          <% if user_signed_in? %>
            <div class="dropdown text-end">
              <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                 data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag "user.png", alt: "userpic", height: "32", class: "rounded-circle" %>
              </a>
              <ul class="dropdown-menu text-small">
                <li>
                  <a class="dropdown-item disabled" href="#">
                    <i class="bi bi-person-circle me-2"></i>
                    <%= current_user.name %>
                    <%= current_user.surname %>
                  </a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <a class="dropdown-item" href="/users/edit">
                    <i class="bi bi-key-fill me-2"></i>
                    <%= t("change_password") %>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item" href="/users/sign_out">
                    <i class="bi bi-box-arrow-right me-2"></i>
                    <%= t("sign_out") %>
                  </a>
                </li>
              </ul>
            </div>
          <% else %>
            <div class="d-flex flex-row gap-2">
              <%= link_to t("sign_up"), new_user_registration_path, class: "btn btn-outline-secondary" %>
              <%= link_to t("login"), new_user_session_path, class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </header>
  <div class="flex-grow-1">
    <%= yield %>
  </div>
  <footer class="text-center pb-2 pt-3 border-top">
    <p class="mb-3 mt-1">Made with ❤️ by
      <a href="https://vitto.dev" target="_blank" rel="noopener noreferrer" class="text-blue-500">Vittorio Lo Mele</a>
      with
      <a href="https://rubyonrails.org" target="_blank" rel="noopener noreferrer" class="text-blue-500">Ruby on Rails</a>
    </p>
  </footer>
</div>
<script>
    <% if flash[:notice] %>
      document.addEventListener("ReadyForToast", () => {
          window.toastr.info("Operazione completata con successo!");
      });
      <% flash.delete(:notice) %>
    <% end %>
    <% if flash[:error] %>
      document.addEventListener("ReadyForToast", () => {
          window.toastr.error(`
            <%= flash[:error] %>
          `);
      });
      <% flash.delete(:alert) %>
    <% end %>
</script>
</body>
</html>